### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by zexcster** [MortenHannemose/pytorch-vfi-cft#6]
6sec 4K 30fps H264 100Mb mov file leads to out of memory error (NVIDIA 1070) WINDOWS 10
Does not depend on the output resolution.
It's Ok in 1080p
The same 4k file works fine  in CPU mode (Mac OS)

not sure if it's a pytorch error

Also,
current version even with Cyclic Fune-Tuning gives much worse results than Twixtor (not pro) for moving horses in front of busy moving backgrounds, e.g. when you tracking horses...
the background just starts floating randomly within the whole frame . Twixtor also ruins it but just in a small area around the horse.

Also does not work good for sparrows, for their fast moving wings. it does not add additional wing positions, instead it just manipulates the opacity level of edge frames, so the first wing position becomes less visible the second one more visible, but no vector changes

probably I need to use another pre-trained model

P.S. I didn't see any visible difference between CFT on and off, just CPU time increased...

**Comment by MortenHannemose** [comment]
The memory issues are just because you don't have enough ram on your GPU for 4k, which is to be expected. It works on CPU because you have more ram on than GPU ram. 

Our model like all other models of course does not work perfectly all the time. In this case it has problem with too large/fast motion, so it can't recognize the object in the two frames. Sorry about that. 
The cyclic fine tuning improves the result in some circumstances, if the generated slowmotion is close, but slightly off.

**Comment by zexcster** [comment]
Thanks
